### ISSUE TITLE
Issue upgrading to 4.1

### ISSUE THREAD

**Issue by martindsouza** [OraOpenSource/apex-nitro#247]
### Issue Description

```
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules\apex-nitro\node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules\apex-nitro\node_modules\glob-watcher\node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN ajv-keywords@3.1.0 requires a peer of ajv@^6.0.0 but none was installed.
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "apex-nitro"
npm ERR! node v6.11.2
npm ERR! npm  v3.10.10
npm ERR! path C:\Users\mdsouza\AppData\Roaming\npm\node_modules\apex-nitro\node_modules\node-sass
npm ERR! code EPERM
npm ERR! errno -4048
npm ERR! syscall rename

npm ERR! Error: EPERM: operation not permitted, rename 'C:\Users\mdsouza\AppData\Roaming\npm\node_modules\apex-nitro\node_modules\node-sass' -> 'C:\Users\mdsouza\AppData\Roaming\npm\node_modules\apex-nitro\node_modules\.node-sass.DELETE'
npm ERR!     at moveAway (C:\Program Files\nodejs\node_modules\npm\lib\install\action\finalize.js:38:5)
npm ERR!     at destStatted (C:\Program Files\nodejs\node_modules\npm\lib\install\action\finalize.js:27:7)
npm ERR!     at C:\Program Files\nodejs\node_modules\npm\node_modules\graceful-fs\polyfills.js:267:18
npm ERR!     at FSReqWrap.oncomplete (fs.js:123:15)
npm ERR!
npm ERR! Error: EPERM: operation not permitted, rename 'C:\Users\mdsouza\AppData\Roaming\npm\node_modules\apex-nitro\node_modules\node-sass' -> 'C:\Users\mdsouza\AppData\Roaming\npm\node_modules\apex-nitro\node_modules\.node-sass.DELETE'
npm ERR!     at Error (native)
npm ERR!  { Error: EPERM: operation not permitted, rename 'C:\Users\mdsouza\AppData\Roaming\npm\node_modules\apex-nitro\node_modules\node-sass' -> 'C:\Users\mdsouza\AppData\Roaming\npm\node_modules\apex-nitro\node_modules\.node-sass.DELETE'
npm ERR!     at moveAway (C:\Program Files\nodejs\node_modules\npm\lib\install\action\finalize.js:38:5)
npm ERR!     at destStatted (C:\Program Files\nodejs\node_modules\npm\lib\install\action\finalize.js:27:7)
npm ERR!     at C:\Program Files\nodejs\node_modules\npm\node_modules\graceful-fs\polyfills.js:267:18
npm ERR!     at FSReqWrap.oncomplete (fs.js:123:15)
npm ERR!
npm ERR! Error: EPERM: operation not permitted, rename 'C:\Users\mdsouza\AppData\Roaming\npm\node_modules\apex-nitro\node_modules\node-sass' -> 'C:\Users\mdsouza\AppData\Roaming\npm\node_modules\apex-nitro\node_modules\.node-sass.DELETE'
npm ERR!     at Error (native) parent: 'apex-nitro' }
npm ERR!
npm ERR! Please try running this command again as root/Administrator.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\mdsouza\Documents\svn_projects\ood-trunk\build\npm-debug.log
npm ERR! code 1
```

### APEX Nitro Version
[Example: v4.0.1]

### Operating System
Windows

### Node Version
v6.11.2

**Comment by martindsouza** [comment]
[npm-debug.log](https://github.com/OraOpenSource/apex-nitro/files/1746493/npm-debug.log)

**Comment by martindsouza** [comment]
Issue was I had apex-nitro running in a different CLI tab.
