### ISSUE TITLE
Launch throws an error in Windows 10 but working excellent in Mac OS

### ISSUE THREAD

**Issue by mahmoudrabie** [OraOpenSource/apex-nitro#259]
### Issue Description
Thanks a lot for this great tool which is working excellent with me on Mac OS.
In Windows 10, I configured the project using
`
apex-nitro config myproject
`
However, whenever I try launching the project it throws an error
`
C:\Users\Mahmoud Rabie>apex-nitro launch myproject

is compiling myproject ...
C:\Users\Mahmoud Rabie\AppData\Roaming\npm\node_modules\apex-nitro\node_modules\async-done\index.js:18
    throw err;
    ^

Error: Unhandled "error" event. ([object Object])
    at Gulp.emit (events.js:186:19)
    at Object.error (C:\Users\Mahmoud Rabie\AppData\Roaming\npm\node_modules\apex-nitro\node_modules\undertaker\lib\helpers\createExtensions.js:61:10)
    at handler (C:\Users\Mahmoud Rabie\AppData\Roaming\npm\node_modules\apex-nitro\node_modules\now-and-later\lib\mapSeries.js:43:14)
    at f (C:\Users\Mahmoud Rabie\AppData\Roaming\npm\node_modules\apex-nitro\node_modules\once\once.js:25:25)
    at f (C:\Users\Mahmoud Rabie\AppData\Roaming\npm\node_modules\apex-nitro\node_modules\once\once.js:25:25)
    at tryCatch (C:\Users\Mahmoud Rabie\AppData\Roaming\npm\node_modules\apex-nitro\node_modules\async-done\index.js:24:15)
    at done (C:\Users\Mahmoud Rabie\AppData\Roaming\npm\node_modules\apex-nitro\node_modules\async-done\index.js:40:12)
    at Domain.onError (C:\Users\Mahmoud Rabie\AppData\Roaming\npm\node_modules\apex-nitro\node_modules\async-done\index.js:51:5)
    at Object.onceWrapper (events.js:315:30)
    at emitOne (events.js:116:13)
`

Is there any special or extra configuration for Windows 10

I would appreciate your help

Regards
Mahmoud

### APEX Nitro Version
APEX Nitro version 4.1.2

### Operating System
Windows 10

### Node Version
v8.9.4

### Browser
Google Chrome 66.0.3359.117

### APEX Version
5.1.4.00.8

### Web Server
Oracle REST Data Services 17.4.1.353.06.48

**Comment by mahmoudrabie** [comment]
Hi Vincent,

Thank for your reply.

**Here is the exported configuration**
```
{
    "mode": "advanced",
    "appURL": "MYAPPURL",
    "srcFolder": "C:\\MYPATH1\\apexnitro\\src",
    "distFolder": "C:\\MYPATH1\\apexnitro\\dist",
    "js": {
        "processor": "default",
        "concat": false,
        "library": false,
        "tsConcat": false
    },
    "css": {
        "language": "css",
        "concat": false
    },
    "browsersync": {
        "notify": false,
        "ghostMode": false
    },
    "header": {
        "enabled": false
    },
    "apex": {
        "openBuilder": true
    },
    "publish": {
        "destination": "application",
        "path": "C:\\MYPATH2\\sqlcl-18.1.1\\sqlcl\\bin\\sql",
        "connectionType": "custom",
        "connectionString": "MYSCHEMA/MYPASSWORD@MYHOST:1521/MYSID"
    }
}
```

The source folder is the same structure from my google drive as I am synchronizing the Win 10 PC and the MAC
It contains multiple folders accessed with no problem from Mac.

I would appreciate your help

Regards
Mahmoud

**Comment by vincentmorneau** [comment]
Mahmoud,

Is your src code confidential? If I could launch your project myself, it would be much easier to debug.

**Comment by vincentmorneau** [comment]
@mahmoudrabie please try again with the newest release (v4.1.4). I have tried with many windows environments and all seems good.
