### ISSUE TITLE
Cannot restart nitro after an exception occurs

### ISSUE THREAD

**Issue by tschf** [OraOpenSource/apex-nitro#287]
### Issue Description

This is happened to me a couple of times and I don't have reliable reproduce steps, so may be an edge case. I'd leave nitro on overnight and come back to find this stack:

```
TypeError: Header name must be a valid HTTP Token ["cookie "]
    at validateHeader (_http_outgoing.js:490:11)
    at ClientRequest.setHeader (_http_outgoing.js:501:3)
    at new ClientRequest (_http_client.js:173:14)
    at Object.request (http.js:38:10)
    at Object.request (https.js:239:15)
    at Array.stream (C:\Users\tschf\AppData\Roaming\npm\node_modules\apex-nit
ro\node_modules\http-proxy\lib\http-proxy\passes\web-incoming.js:111:74)
    at ProxyServer.<anonymous> (C:\Users\tschf\AppData\Roaming\npm\node_modul
es\apex-nitro\node_modules\http-proxy\lib\http-proxy\index.js:80:21)
    at handle (C:\Users\tschf\AppData\Roaming\npm\node_modules\apex-nitro\nod
e_modules\browser-sync\dist\server\proxy-server.js:77:23)
    at call (C:\Users\tschf\AppData\Roaming\npm\node_modules\apex-nitro\node_
modules\connect\index.js:239:7)
    at next (C:\Users\tschf\AppData\Roaming\npm\node_modules\apex-nitro\node_
modules\connect\index.js:183:5)
_http_outgoing.js:494
    throw new Error('Can\'t set headers after they are sent.');
    ^

Error: Can't set headers after they are sent.
    at validateHeader (_http_outgoing.js:494:11)
    at ClientRequest.setHeader (_http_outgoing.js:501:3)
    at apexProxyReq (C:\Users\tschf\AppData\Roaming\npm\node_modules\apex-nit
ro\lib\gulp\browsersync.js:20:7)
    at C:\Users\tschf\AppData\Roaming\npm\node_modules\apex-nitro\node_module
s\browser-sync\dist\server\proxy-server.js:121:24
    at List.__iterate (C:\Users\tschf\AppData\Roaming\npm\node_modules\apex-n
itro\node_modules\immutable\dist\immutable.js:2206:13)
    at List.forEach (C:\Users\tschf\AppData\Roaming\npm\node_modules\apex-nit
ro\node_modules\immutable\dist\immutable.js:4381:19)
    at ProxyServer.<anonymous> (C:\Users\tschf\AppData\Roaming\npm\node_modul
es\apex-nitro\node_modules\browser-sync\dist\server\proxy-server.js:119:17)
    at ProxyServer.emit (C:\Users\tschf\AppData\Roaming\npm\node_modules\apex
-nitro\node_modules\eventemitter3\index.js:119:35)
    at ClientRequest.<anonymous> (C:\Users\tschf\AppData\Roaming\npm\node_mod
ules\apex-nitro\node_modules\http-proxy\lib\http-proxy\passes\web-incoming.js:11
7:27)
    at emitOne (events.js:121:20)
```

The command prompt becomes somewhat unresponsive - I can't do ctrl+c or ctrl+d to terminate the process.

I also can't seem to kill the node process - I get access is denied. I tried a number of options to kill including with process hacker, but get the following:

![image](https://user-images.githubusercontent.com/1747643/45432294-84317f80-b677-11e8-9f07-fdfae488ebca.png)

If I try and start a new instance of nitro, I get the following:
```
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE :::4001
    at Object._errnoException (util.js:1022:11)
    at _exceptionWithHostPort (util.js:1044:20)
    at Server.setupListenHandle [as _listen2] (net.js:1351:14)
    at listenInCluster (net.js:1392:12)
    at Server.listen (net.js:1476:7)
    at module.exports.plugin (C:\Users\tschafer\AppData\Roaming\npm\node_modules
\apex-nitro\node_modules\browser-sync\dist\server\index.js:27:25)
    at Object.startServer [as fn] (C:\Users\tschafer\AppData\Roaming\npm\node_mo
dules\apex-nitro\node_modules\browser-sync\dist\async.js:177:52)
    at C:\Users\tschafer\AppData\Roaming\npm\node_modules\apex-nitro\node_module
s\browser-sync\dist\browser-sync.js:120:14
    at iterate (C:\Users\tschafer\AppData\Roaming\npm\node_modules\apex-nitro\no
de_modules\browser-sync\dist\utils.js:253:13)
    at C:\Users\tschafer\AppData\Roaming\npm\node_modules\apex-nitro\node_module
s\browser-sync\dist\utils.js:264:25
```

My recourse seems to be restarting my system.

### APEX Nitro Version
APEX Nitro version 4.1.5

### Operating System
Windows 7

### Node Version
v8.9.4

### Browser
Firefox 62

### APEX Version
5.0

**Comment by vincentmorneau** [comment]
Quick Q before I do serious investigation: do you have only one APEX Nitro project running at that time or multiple?

**Comment by vincentmorneau** [comment]
Closing now that v5 is in development and I have never been able to reproduce
