### ISSUE TITLE
Support for headless APEX Nitro

### ISSUE THREAD

**Issue by martindsouza** [OraOpenSource/apex-nitro#296]
### Issue Description
If running in Docker (#231) or a VM without X (see issue #216) don't auto launch the browser.

Error message you get when running APEX Nitro in a headless instance:

```bash
> apex-nitro config

You can configure your project here: http://localhost:3000
(node:1) UnhandledPromiseRejectionWarning: Error: Exited with code 3
    at ChildProcess.cp.once.code (/home/node/.npm-global/lib/node_modules/apex-nitro/node_modules/node-package-configurator/node_modules/opn/index.js:84:13)
    at Object.onceWrapper (events.js:277:13)
    at ChildProcess.emit (events.js:189:13)
    at ChildProcess.EventEmitter.emit (domain.js:441:20)
    at maybeClose (internal/child_process.js:970:16)
    at Socket.stream.socket.on (internal/child_process.js:389:11)
    at Socket.emit (events.js:189:13)
    at Socket.EventEmitter.emit (domain.js:441:20)
    at Pipe._handle.close (net.js:597:12)
(node:1) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:1) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

### APEX Nitro Version
Latest

### Operating System
`node:10-alpine`

**Comment by vincentmorneau** [comment]
Will add a headless mode to avoid opening the browser automatically.
