### ISSUE TITLE
apex-nitro upload error

### ISSUE THREAD

**Issue by martindsouza** [OraOpenSource/apex-nitro#341]
### Issue Description
When running `apex-nitro upload` getting following error:

```bash
(node:11083) UnhandledPromiseRejectionWarning: TypeError: Cannot destructure property `nomin` of 'undefined' or 'null'.
    at module.exports (/Users/giffy/git/oraopensource/apex-nitro/lib/commands/launch.js:18:33)
    at launchUpload (/Users/giffy/git/oraopensource/apex-nitro/lib/commands/upload.js:46:4)
    at Object.module.exports [as upload] (/Users/giffy/git/oraopensource/apex-nitro/lib/commands/upload.js:133:4)
    at Command.commander.command.description.action (/Users/giffy/git/oraopensource/apex-nitro/bin/apex-nitro.js:77:13)
    at Command.listener [as _actionHandler] (/Users/giffy/git/oraopensource/apex-nitro/node_modules/commander/index.js:422:31)
    at Command._parseCommand (/Users/giffy/git/oraopensource/apex-nitro/node_modules/commander/index.js:975:14)
    at Command._dispatchSubcommand (/Users/giffy/git/oraopensource/apex-nitro/node_modules/commander/index.js:926:18)
    at Command._parseCommand (/Users/giffy/git/oraopensource/apex-nitro/node_modules/commander/index.js:943:12)
    at Command.parse (/Users/giffy/git/oraopensource/apex-nitro/node_modules/commander/index.js:778:10)
    at Object.<anonymous> (/Users/giffy/git/oraopensource/apex-nitro/bin/apex-nitro.js:80:11)
(node:11083) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:11083) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

### APEX Nitro Version
5.0.1

### Operating System
mac osx

### Node Version
v10.15.1

### Browser
NA

### APEX Version
NA

### Web Server
NA

### Project configuration screenshot

`apexnitro.cred.json`

```json
{
  "path": "sqlcl",
  "username": "martin",
  "password": "pass",
  "connectionString": "martin/password@db_high"
}
```

**Comment by martindsouza** [comment]
This seems to happen with `launch` as well. After some investigation it looks like a new config is required (that is not automatically generated with an `init`:

`apexnitro.config.json`:

```
...
"srcFolder": "./www",
// distFolder is the new config
"distFolder": "./www",
```

_Note: in this case I set `distFolder` to be the same as `srcFolder` or else nothing loaded as the concept of `distFolder` doesn't exist in a basic setting_

Then in `lib/util/validatuions.js` needed to comment out the first check in `isDistFolderValid(config)` (around Line 42):

```js
...
isDistFolderValid(config) {
		// MDSOUZA: Commenting this out fixed issue
		// if (path.resolve(config.distFolder) === path.resolve(config.srcFolder)) {
		// 	throw new Error(
		// 		`Your project configuration srcFolder (${path.resolve(
		// 			config.srcFolder
		// 		)}) is equal to distFolder (${path.resolve(
		// 			config.distFolder
		// 		)}). Please choose a different distFolder location.`
		// 	);
		// }

		const relative = path.relative(
```

I understand why the validation is in place but I think that distFolder should only be required in advanced mode and this is causing all the issues.
